dist: trusty
language: scala
sudo: false

scala: 2.13.1

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - $(npm bin)/tsc samples/*.d.ts

before_cache:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 12
  - nvm use 12
  - npm install typescript@3.7.5

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - node_modules
